import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import RootLayoutProtect from "./protect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bilds",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <RootLayoutProtect>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center`}
        >
          {children}
          <Toaster position="top-right" />
        </body>
      </html>
    </RootLayoutProtect>
  );
}
